# Generated by Django 2.2 on 2020-08-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_profile',
            field=models.URLField(null=True, verbose_name='Профиль на GitHub'),
        ),
    ]
