# Generated by Django 2.2 on 2020-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200820_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='О себе'),
        ),
    ]
